### ISSUE TITLE
Nice app, I’m considering integrating this with VesselAlert

### ISSUE THREAD

**Issue by kx1t** [jeff-luszcz/AISTropoAlert#1]
Hi there,

I came across your short script/app via the AisCatcher website. Great idea! I’m considering to incorporate it into my vessel notification app/container called [VesselAlert](https://github.com/SDR-enthusiasts/docker-vesselalert/) , of course with proper attributions under your GPL license. One of the improvements I’m thinking of is to keep a rolling (12-hour for example) max distance and only send a notification if the actual distance is > minimum distance and if it’s at least (say) 25 nm further than the last measured max distance. That way the notifications can be limited to only meaningful ones. 

This would be a great add to VesselAlert and easy to implement as I already have Mastodon and Discord notifications. (See for example https://airwaves.social/@bostonharbor )

Thanks again; feel free to close this (non-) issue after you read it. 

Ramon

**Comment by jeff-luszcz** [comment]
Sounds great, I hope you find the script useful!
