### ISSUE TITLE
the ships function won't work correctly

### ISSUE THREAD

**Issue by dziban303** [jeff-luszcz/AISTropoAlert#2]
Hi, 

The [SHIPS function](https://github.com/jeff-luszcz/AISTropoAlert/blob/1ed4837b900d7af49645ec10877046e51f82b725/AISTropoAlert.sh#L44) won't work correctly with `sort -r`, it needs to be `sort -nr` for numeric sort or weird things can happen, like 9 miles coming before 10 miles.

**Comment by jeff-luszcz** [comment]
Thanks, made the change!
